/* The labyrinth: a deliberately bad way to browse a pile of links. One link per
   page, move between pages by swiping up/down/left/right. Only some directions
   exist from any given page, and a few of them lie.

   This file is the engine and nothing else. The contents — links, blocks, and
   where they sit — live in map.js, which is generated by
   _tools/labyrinth-editor.html and loaded before this. */

(function () {
  'use strict';

  var DIRS = { up: [0, -1], down: [0, 1], left: [-1, 0], right: [1, 0] };
  var DIR_NAMES = ['up', 'down', 'left', 'right'];
  var OPPOSITE = { up: 'down', down: 'up', left: 'right', right: 'left' };
  var KEY = 'ariadne';

  /* how many tunnels in a row before we give up and put the visitor somewhere */
  var TUNNEL_HOPS = 12;
  var TUNNEL_DEFAULTS = { color: '#000000', ms: 500, fx: 100, effect: 'fade', back: 0 };
  var EFFECTS = ['fade', 'crossfade', 'slide', 'iris', 'flicker'];

  /* --------------------------------------------------------------- layouts */

  /* A block can arrange its contents on a grid this size instead of using the
     one fixed centred stack. The caps are deliberate: a block that can hold
     anything stops being a block. */
  var GRID = { cols: 12, rows: 20 };
  var EL_TYPES = ['title', 'line', 'para', 'image', 'button'];
  var EL_LIMITS = { title: 1, line: 2, para: 2, image: 3, button: 1 };
  var EL_DEFAULTS = { size: 3, align: 'center', valign: 'middle', fit: 'contain' };
  var BUTTON_ACTIONS = ['url', 'goto', 'random'];

  function hasLayout(cell) {
    return !!(cell && cell.layout && cell.layout.length);
  }

  /* Quotes too, not just angle brackets: this also guards the href="" a block's
     link goes into, and a url with a " in it would close the attribute early. */
  function escapeHtml(text) {
    var div = document.createElement('div');
    div.textContent = text == null ? '' : text;
    return div.innerHTML.replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }

  /* Only these can end up in an href. Everything else — javascript:, data:, and
     anything else someone gets clever with — is refused, and the link renders as
     the plain text it was written as. Relative paths are ours, so they pass. */
  function safeUrl(url) {
    var raw = String(url == null ? '' : url).trim();
    if (!raw) return '';
    if (/^(https?:|mailto:)/i.test(raw)) return raw;

    /* a scheme we don't allow — but a bare "foo.html" or "#x" has no scheme,
       and ":" can't appear before the first "/" without one */
    return /^[a-z][a-z0-9+.-]*:/i.test(raw) ? '' : raw;
  }

  var MARKUP = {
    /* The url part allows one level of nested parens, so a wikipedia link like
       Foo_(bar) survives — and, less obviously, so that javascript:alert(1) is
       captured whole and gets refused, instead of matching up to the first ")"
       and leaving a stray character behind that hides the rejection. */
    link: /\[([^\]]*)\]\(((?:[^()\s]|\([^()\s]*\))*)\)/g,
    bold: /\*\*([^*]+)\*\*/g,
    italic: /\*([^*]+)\*/g
  };

  /* The small formatting subset paragraphs are written in. Everything is escaped
     first and the markup applied to the escaped text, so nothing an author types
     can become an element — the only tags here are ones we emit.

     Exported, because the site, the editor's preview and maze-check all have to
     agree on what a paragraph says, the same way they all defer to resolveExit()
     about where a swipe goes. */
  function renderMarkup(text) {
    var paragraphs = String(text == null ? '' : text).split(/\n\s*\n/);

    return paragraphs.map(function (para) {
      var html = escapeHtml(para);

      html = html.replace(MARKUP.link, function (whole, label, url) {
        var href = safeUrl(unescapeEntities(url));
        if (!href) return label || whole;
        return '<a href="' + escapeHtml(href) + '" target="_blank" rel="noopener noreferrer">' +
          (label || escapeHtml(href)) + '</a>';
      });

      html = html.replace(MARKUP.bold, '<strong>$1</strong>');
      html = html.replace(MARKUP.italic, '<em>$1</em>');

      return '<p>' + html.replace(/\n/g, '<br>') + '</p>';
    }).join('');
  }

  /* escapeHtml() ran over the url before the link pattern matched it, so what we
     captured is entity-encoded. safeUrl() has to see the real thing to judge it. */
  function unescapeEntities(s) {
    return String(s)
      .replace(/&quot;/g, '"').replace(/&#39;/g, "'")
      .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
      .replace(/&amp;/g, '&');
  }

  function markupUrls(text) {
    var out = [];
    String(text == null ? '' : text).replace(MARKUP.link, function (whole, label, url) {
      var href = safeUrl(url);
      if (href) out.push(href);
      return whole;
    });
    return out;
  }

  /* Everything that can be wrong with a block's arrangement, as [severity, text]
     pairs. Lives here rather than in the editor because _tools/maze-check.js
     checks the same list — two copies of these rules drifting apart is exactly
     the failure the shared resolveExit() exists to prevent. */
  function layoutProblems(cell, index) {
    var out = [];
    if (!hasLayout(cell)) return out;

    if (isTunnel(cell)) {
      out.push(['bad', cell.id + ' is a tunnel with an arrangement on it — nobody stops long enough to see it']);
    }

    var counts = {};
    cell.layout.forEach(function (el, i) {
      var where = cell.id + ' element ' + (i + 1) + ' (' + el.type + ')';
      counts[el.type] = (counts[el.type] || 0) + 1;

      if (EL_TYPES.indexOf(el.type) === -1) {
        out.push(['bad', where + ' is not a kind of element that exists']);
        return;
      }

      if (el.x < 0 || el.y < 0 || el.w < 1 || el.h < 1 ||
          el.x + el.w > GRID.cols || el.y + el.h > GRID.rows) {
        out.push(['bad', where + ' falls off the grid — it would be clipped']);
      }

      if (el.type === 'image') {
        if (!el.src) out.push(['warn', where + ' has no image chosen']);
        else if (!safeUrl(el.src)) out.push(['bad', where + ' has an image path that will be refused: ' + el.src]);
      } else if (!String(el.text || '').trim()) {
        out.push(['warn', where + ' has no text in it']);
      }

      if (el.href && !safeUrl(el.href)) {
        out.push(['bad', where + ' links somewhere that will be refused: ' + el.href]);
      }

      if (el.type !== 'button') return;

      var action = el.action || 'url';
      if (BUTTON_ACTIONS.indexOf(action) === -1) {
        out.push(['bad', where + ' has an action that does not exist']);
        return;
      }

      if (action === 'goto') {
        /* The one that really matters. Every other mistake here is cosmetic; a
           button offering a way onward that goes nowhere is a dead end the
           visitor can actually press. */
        if (!el.to) out.push(['bad', where + ' is a go-to button with no block chosen']);
        else if (!index.byId.get(el.to)) out.push(['bad', where + ' points at ' + el.to + ', which no longer exists']);
        else if (isTunnel(index.byId.get(el.to))) out.push(['warn', where + ' points at ' + el.to + ', a tunnel — the visitor gets routed straight through it']);
      } else if (action === 'url') {
        if (!el.to) out.push(['warn', where + ' is a link button with no link on it']);
        else if (!safeUrl(el.to)) out.push(['bad', where + ' has a destination that will be refused: ' + el.to]);
      }
    });

    Object.keys(counts).forEach(function (type) {
      var cap = EL_LIMITS[type];
      if (cap !== undefined && counts[type] > cap) {
        out.push(['bad', cell.id + ' has ' + counts[type] + ' ' + type + ' elements, more than the ' + cap + ' allowed']);
      }
    });

    return out;
  }

  /* Every url a block points at, wherever it's hiding. Once a block can carry a
     layout its link is no longer just `cell.link` — it can sit on an element, on
     a button, or inline in a paragraph — and the editor's "unused link" badge is
     only honest if it looks in all of those places. */
  function cellUrls(cell) {
    var out = [];
    if (!cell) return out;
    if (cell.link) out.push(cell.link);

    (cell.layout || []).forEach(function (el) {
      if (el.href) out.push(el.href);
      if (el.type === 'button' && el.action === 'url' && el.to) out.push(el.to);
      if (el.type === 'para') out.push.apply(out, markupUrls(el.text));
    });

    return out.filter(function (url, i) { return out.indexOf(url) === i; });
  }

  function decodeMaze(blob) {
    var bin = atob(blob);
    var bytes = new Uint8Array(bin.length);
    for (var i = 0; i < bin.length; i++) {
      bytes[i] = bin.charCodeAt(i) ^ KEY.charCodeAt(i % KEY.length);
    }
    return JSON.parse(new TextDecoder().decode(bytes));
  }

  function encodeMaze(maze) {
    var bytes = new TextEncoder().encode(JSON.stringify(maze));
    var bin = '';
    for (var i = 0; i < bytes.length; i++) {
      bin += String.fromCharCode(bytes[i] ^ KEY.charCodeAt(i % KEY.length));
    }
    return btoa(bin);
  }

  /* map.js defines both of these. The blob is the real map; the readable object
     beside it is a decoy, kept only as something to fall back on if the blob is
     ever mangled. Guarded with typeof so the editor and _tools/maze-check.js
     don't explode when map.js hasn't been loaded. */
  function loadMaze() {
    try {
      return decodeMaze(LABYRINTH_CACHE);
    } catch (err) {
      return typeof LABYRINTH_MAP !== 'undefined' ? LABYRINTH_MAP : { start: null, links: [], cells: [] };
    }
  }

  /* ------------------------------------------------------------ maze lookup */

  /* Wraps a maze in id/coordinate lookups plus the one movement rule everything
     else defers to. The editor and _tools/maze-check.js call this too, so the
     three can never disagree about where a swipe leads. */
  function indexMaze(maze) {
    var byId = new Map();
    var byXY = new Map();

    maze.cells.forEach(function (cell) {
      byId.set(cell.id, cell);
      byXY.set(cell.x + ',' + cell.y, cell);
    });

    return {
      maze: maze,
      byId: byId,
      byXY: byXY,

      /* 1. an explicit exit id wins  -> wormhole, can land anywhere
         2. an explicit null          -> hard wall
         3. otherwise                 -> the neighbouring square, if one exists */
      resolveExit: function (cell, dir) {
        if (cell.exits && Object.prototype.hasOwnProperty.call(cell.exits, dir)) {
          var target = cell.exits[dir];
          return target ? byId.get(target) || null : null;
        }
        var step = DIRS[dir];
        return byXY.get((cell.x + step[0]) + ',' + (cell.y + step[1])) || null;
      }
    };
  }

  function reachableFrom(index, startId) {
    var start = index.byId.get(startId) || index.maze.cells[0];
    if (!start) return new Set();

    var seen = new Set([start.id]);
    var queue = [start];

    while (queue.length) {
      var cell = queue.shift();
      DIR_NAMES.forEach(function (dir) {
        var next = index.resolveExit(cell, dir);
        if (next && !seen.has(next.id)) {
          seen.add(next.id);
          queue.push(next);
        }
      });
    }
    return seen;
  }

  /* ---------------------------------------------------------------- tunnels */

  /* A tunnel is a block you pass through rather than stop in. It shows its
     message for a moment, then hands you to one of its neighbours at random. */
  function isTunnel(cell) {
    return !!(cell && cell.tunnel);
  }

  /* Pale tunnel colors need dark text or the message disappears. */
  function isLight(color) {
    var hex = String(color || '').replace('#', '');
    if (hex.length === 3) hex = hex[0] + hex[0] + hex[1] + hex[1] + hex[2] + hex[2];
    if (!/^[0-9a-f]{6}$/i.test(hex)) return false;

    var r = parseInt(hex.slice(0, 2), 16);
    var g = parseInt(hex.slice(2, 4), 16);
    var b = parseInt(hex.slice(4, 6), 16);
    return (r * 0.299 + g * 0.587 + b * 0.114) > 150;
  }

  function tunnelSetting(cell, key) {
    var conf = cell.tunnel || {};
    return conf[key] === undefined || conf[key] === null ? TUNNEL_DEFAULTS[key] : conf[key];
  }

  /* Weighted pick among the neighbours a tunnel actually has.
     `entryDir` is the direction you were travelling when you arrived, so the way
     back out is the opposite of it — weighted by `back`, which defaults to 0. */
  function pickExit(index, cell, entryDir, rng) {
    var exits = [];
    DIR_NAMES.forEach(function (dir) {
      var next = index.resolveExit(cell, dir);
      if (next) exits.push({ dir: dir, cell: next });
    });
    if (!exits.length) return null;

    var backDir = entryDir ? OPPOSITE[entryDir] : null;
    var weights = (cell.tunnel || {}).weights || {};

    var forward = exits.filter(function (e) { return e.dir !== backDir; });
    var back = exits.filter(function (e) { return e.dir === backDir; })[0];

    var pool = forward.map(function (e) {
      var w = weights[e.dir];
      return { exit: e, weight: typeof w === 'number' && w >= 0 ? w : 1 };
    });
    if (back) pool.push({ exit: back, weight: Math.max(0, tunnelSetting(cell, 'back')) });

    var total = pool.reduce(function (sum, p) { return sum + p.weight; }, 0);

    /* Everything weighted to zero. Split evenly among the ways onward, and only
       hand them back the way they came if there is no other way at all. */
    if (total <= 0) {
      var evens = forward.length ? forward : (back ? [back] : []);
      if (!evens.length) return null;
      return evens[Math.min(evens.length - 1, Math.floor(rng() * evens.length))];
    }

    var roll = rng() * total;
    for (var i = 0; i < pool.length; i++) {
      roll -= pool[i].weight;
      if (roll < 0) return pool[i].exit;
    }
    return pool[pool.length - 1].exit;
  }

  /* Walks a run of tunnels to the chamber on the far side. Safe to call on any
     block: a chamber returns itself with an empty path. `dest` comes back null
     only if the tunnels never reach a chamber, which the caller treats as "stay
     where you were" rather than stranding anyone. */
  function tunnelRoute(index, cell, entryDir, rng) {
    var random = rng || Math.random;
    var path = [];
    var dirs = []; /* dirs[i] is the way you leave path[i] */
    var at = cell;
    var dir = entryDir || null;

    for (var hop = 0; hop < TUNNEL_HOPS && isTunnel(at); hop++) {
      path.push(at);

      var pick = pickExit(index, at, dir, random);
      if (!pick) break;

      dirs.push(pick.dir);
      at = pick.cell;
      dir = pick.dir;
    }

    return { path: path, dirs: dirs, dest: isTunnel(at) ? null : at, dir: dir };
  }

  /* --------------------------------------------------------------- contents */

  /* Cells point at a link by url rather than carrying their own copy of it, so
     one link can sit on several blocks and editing it once fixes all of them.
     A cell can override the title or add a note on top of that. */
  function buildLinkIndex(maze) {
    var links = new Map();
    (maze.links || []).forEach(function (link) {
      links.set(link.url, link);
    });
    return links;
  }

  /* A cell with no link at all is a text-only page — somewhere to put a line of
     nonsense with nothing to click. */
  function cellContent(cell, links) {
    var link = links.get(cell.link) || {};
    var url = cell.link || link.url || '';
    return {
      url: url,
      /* a tunnel with nothing written on it is just a colored flash, not a "???" */
      title: cell.title || link.title || url || (isTunnel(cell) ? '' : '???'),
      description: cell.description || link.description || '',
      note: cell.note || ''
    };
  }

  /* ---------------------------------------------------------------- the pack */

  var ITEMS = [
    { icon: '🪢', name: 'escape rope', escape: true, flavor: 'you climb. you arrive back at the beginning.' },
    { icon: '🗝', name: 'bent key', flavor: "it doesn't fit anything here." },
    { icon: '🔋', name: 'dead battery', flavor: 'no charge. you keep it anyway.' },
    { icon: '🗺', name: 'half a map', flavor: 'the useful half is missing.' },
    { icon: '🧾', name: 'a receipt', flavor: 'for something you do not remember buying.' }
  ];

  /* ------------------------------------------------------------------ state */

  var STORAGE_KEY = 'labyrinth-cell';
  var SWIPE_THRESHOLD = 50;

  var index = null;
  var links = null;
  var current = null;
  var active = false;
  var moving = false;
  var previewing = false;  /* running inside the editor's test button */
  var onPreviewExit = null;

  var root, stage, veil, pack, inventory, flavorLine;

  /* ------------------------------------------------------------- rendering */

  function elSetting(el, key) {
    return el[key] === undefined || el[key] === null || el[key] === '' ? EL_DEFAULTS[key] : el[key];
  }

  /* One positioned element, as an HTML string. The editor's layout overlay calls
     this too, so what you drag around in the editor is the real thing rather
     than a sketch of it that can drift out of step. `assetBase` is a prefix for
     relative image paths — empty on the site, "../" in the editor, which sits a
     folder deeper than the images do. */
  function buildElement(el, assetBase) {
    var base = assetBase || '';
    var pos =
      'grid-column:' + (Number(el.x) + 1) + '/span ' + Math.max(1, Number(el.w) || 1) + ';' +
      'grid-row:' + (Number(el.y) + 1) + '/span ' + Math.max(1, Number(el.h) || 1);

    var attrs =
      ' class="lab-el lab-el-' + el.type + '"' +
      ' style="' + pos + '"' +
      ' data-size="' + elSetting(el, 'size') + '"' +
      ' data-align="' + elSetting(el, 'align') + '"' +
      ' data-valign="' + elSetting(el, 'valign') + '"';

    return '<div' + attrs + '>' + elementBody(el, base) + '</div>';
  }

  function elementBody(el, base) {
    if (el.type === 'para') return renderMarkup(el.text);

    if (el.type === 'button') return buttonBody(el);

    if (el.type === 'image') {
      var src = safeUrl(el.src);
      if (!src) return '';
      if (!/^(https?:|mailto:)/i.test(src)) src = base + src;

      var img = '<img class="lab-el-img" src="' + escapeHtml(src) + '"' +
        ' alt="' + escapeHtml(el.alt || '') + '"' +
        ' style="object-fit:' + escapeHtml(elSetting(el, 'fit')) + '">';
      return wrapHref(el, img);
    }

    /* title and line: one run of text, no inline markup */
    return wrapHref(el, '<span class="lab-el-text">' + escapeHtml(el.text) + '</span>');
  }

  function wrapHref(el, inner) {
    var href = safeUrl(el.href);
    if (!href) return inner;

    return '<a class="lab-el-link" href="' + escapeHtml(href) +
      '" target="_blank" rel="noopener noreferrer">' + inner + '</a>';
  }

  /* A url button is a real anchor so it behaves like one; the two that move you
     around the maze are buttons the stage's click handler picks up. */
  function buttonBody(el) {
    var label = '<span class="lab-btn-label">' + escapeHtml(el.text || '') + '</span>';

    if (el.action === 'goto') {
      return '<button class="lab-btn" data-goto="' + escapeHtml(el.to || '') + '">' + label + '</button>';
    }
    if (el.action === 'random') {
      return '<button class="lab-btn" data-random="1">' + label + '</button>';
    }

    var href = safeUrl(el.to);
    if (!href) return '<span class="lab-btn is-dead">' + label + '</span>';

    return '<a class="lab-btn" href="' + escapeHtml(href) +
      '" target="_blank" rel="noopener noreferrer">' + label + '</a>';
  }

  function buildPage(cell) {
    var page = document.createElement('article');
    page.className = 'lab-page';

    /* A tunnel gives you no say in where you go, so it gets no arrows. */
    var arrows = isTunnel(cell) ? '' : DIR_NAMES.filter(function (dir) {
      return !!index.resolveExit(cell, dir);
    }).map(function (dir) {
      return '<button class="lab-arrow lab-arrow-' + dir + '" data-dir="' + dir +
        '" aria-label="go ' + dir + '"></button>';
    }).join('');

    if (isTunnel(cell)) {
      var color = tunnelSetting(cell, 'color');
      page.classList.add('lab-tunnel');
      page.style.background = color;
      if (isLight(color)) page.classList.add('is-light');
    }

    /* A block that arranges its own contents gets no page-wide anchor — that
       would swallow the button and every inline link inside it. */
    if (hasLayout(cell)) {
      var base = (root && root.dataset.assetBase) || '';
      page.classList.add('lab-laid-out');
      page.innerHTML =
        '<div class="lab-canvas">' +
          cell.layout.map(function (el) { return buildElement(el, base); }).join('') +
        '</div>' + arrows;
      return page;
    }

    var content = cellContent(cell, links);

    var inner =
      '<span class="lab-title">' + escapeHtml(content.title) + '</span>' +
      (content.description ? '<span class="lab-desc">' + escapeHtml(content.description) + '</span>' : '');

    var body = content.url
      ? '<a class="lab-link" href="' + escapeHtml(content.url) + '" target="_blank" rel="noopener noreferrer">' + inner + '</a>'
      : '<div class="lab-link lab-text">' + inner + '</div>';

    page.innerHTML =
      '<div class="lab-page-inner">' + body +
        (content.note ? '<p class="lab-note">' + escapeHtml(content.note) + '</p>' : '') +
      '</div>' + arrows;

    return page;
  }

  var ENTER = { up: 'translateY(-100%)', down: 'translateY(100%)', left: 'translateX(-100%)', right: 'translateX(100%)' };
  var LEAVE = { up: 'translateY(100%)', down: 'translateY(-100%)', left: 'translateX(100%)', right: 'translateX(-100%)' };

  function showCell(cell, dir) {
    var old = stage.querySelector('.lab-page');
    var page = buildPage(cell);

    current = cell;
    remember(cell);

    if (!old) {
      stage.appendChild(page);
      return;
    }

    moving = true;
    page.style.transform = ENTER[dir];
    stage.appendChild(page);

    /* two frames: one to get the start transform committed, one to animate off it */
    requestAnimationFrame(function () {
      requestAnimationFrame(function () {
        old.classList.add('is-leaving');
        old.style.transform = LEAVE[dir];
        page.style.transform = '';
      });
    });

    setTimeout(function () {
      old.remove();
      moving = false;
    }, 360);
  }

  /* ------------------------------------------------------ tunnel transitions */

  /* Swaps in `page` using one of the five effects, then calls done().
     fade and iris drive the veil; the rest animate the pages themselves. */
  function present(page, effect, dir, ms, done) {
    var old = stage.querySelector('.lab-page');
    var half = Math.max(1, Math.round(ms / 2));

    function land() {
      if (old) old.remove();
      done();
    }

    if (effect === 'fade' || effect === 'iris') {
      veil.className = 'lab-veil is-' + effect;
      veil.style.transitionDuration = half + 'ms';

      requestAnimationFrame(function () {
        veil.classList.add('is-closed');

        setTimeout(function () {
          if (old) old.remove();
          stage.appendChild(page);
          veil.classList.remove('is-closed');
          setTimeout(function () {
            veil.className = 'lab-veil';
            done();
          }, half);
        }, half);
      });
      return;
    }

    if (effect === 'slide') {
      page.style.transform = ENTER[dir] || ENTER.down;
      page.style.transition = 'transform ' + ms + 'ms ease';
      stage.appendChild(page);

      requestAnimationFrame(function () {
        requestAnimationFrame(function () {
          if (old) {
            old.style.transition = 'transform ' + ms + 'ms ease';
            old.style.transform = LEAVE[dir] || LEAVE.down;
          }
          page.style.transform = '';
        });
      });
      setTimeout(land, ms);
      return;
    }

    if (effect === 'flicker') {
      page.style.animation = 'lab-flicker ' + ms + 'ms steps(1, end)';
      stage.appendChild(page);
      setTimeout(function () {
        page.style.animation = '';
        land();
      }, ms);
      return;
    }

    /* crossfade, and the fallback for anything unrecognised */
    page.style.opacity = '0';
    page.style.transition = 'opacity ' + ms + 'ms ease';
    stage.appendChild(page);

    requestAnimationFrame(function () {
      requestAnimationFrame(function () { page.style.opacity = '1'; });
    });
    setTimeout(function () {
      page.style.transition = '';
      page.style.opacity = '';
      land();
    }, ms);
  }

  /* Two independent settings. `fx` is how long a transition takes, played once
     on the way in and once on the way out; `ms` is how long the tunnel sits
     there in between. Door to door a tunnel costs fx + ms + fx. */
  function tunnelTiming(cell) {
    return {
      edge: Math.max(0, Number(tunnelSetting(cell, 'fx')) || 0),
      hold: Math.max(0, Number(tunnelSetting(cell, 'ms')) || 0)
    };
  }

  /* Walks the route a tunnel leads to, playing each one in turn. Entering a
     tunnel uses that tunnel's effect; the last one owns the hand-off into the
     chamber on the far side. */
  function playTunnel(tunnel, dir) {
    var route = tunnelRoute(index, tunnel, dir, Math.random);
    var dest = route.dest || current; /* nothing but tunnels — put them back */

    moving = true;

    function finish() {
      current = dest;
      remember(dest);
      moving = false;
    }

    /* Tunnel i is on screen. Hold it, then transition out into whatever is next
       — which is what puts tunnel i+1 on screen, so that one goes straight to
       its own hold rather than being presented twice. */
    function hold(i) {
      var cell = route.path[i];
      var timing = tunnelTiming(cell);
      var effect = tunnelSetting(cell, 'effect');
      var last = i === route.path.length - 1;
      var onward = route.dirs[i] || dir;

      setTimeout(function () {
        present(buildPage(last ? dest : route.path[i + 1]), effect, onward, timing.edge, function () {
          if (last) finish();
          else hold(i + 1);
        });
      }, timing.hold);
    }

    if (!route.path.length) {
      finish();
      return;
    }

    var first = route.path[0];
    present(buildPage(first), tunnelSetting(first, 'effect'), dir, tunnelTiming(first).edge, function () {
      hold(0);
    });
  }

  function remember(cell) {
    if (previewing) return; /* a test run shouldn't move the real visitor's bookmark */
    try { sessionStorage.setItem(STORAGE_KEY, cell.id); } catch (err) { /* private mode */ }
  }

  function travelTo(next, dir) {
    if (isTunnel(next)) playTunnel(next, dir);
    else showCell(next, dir);
  }

  function move(dir) {
    if (!active || moving) return;

    var next = index.resolveExit(current, dir);
    if (!next) {
      bounce(dir);
      return;
    }
    travelTo(next, dir);
  }

  /* The two button actions that move you. Both arrive the way the escape rope
     does, and both go through travelTo() so landing on a tunnel still plays it. */
  function jumpTo(cellId) {
    if (!active || moving) return;

    var next = index.byId.get(cellId);
    if (next) travelTo(next, 'up');
  }

  function jumpAnywhere() {
    if (!active || moving) return;

    var chambers = index.maze.cells.filter(function (c) {
      return !isTunnel(c) && c !== current;
    });
    if (!chambers.length) return;

    travelTo(chambers[Math.floor(Math.random() * chambers.length)], 'up');
  }

  function bounce(dir) {
    var page = stage.querySelector('.lab-page');
    if (!page) return;

    page.classList.remove('is-bouncing-up', 'is-bouncing-down', 'is-bouncing-left', 'is-bouncing-right');
    void page.offsetWidth; /* restart the animation */
    page.classList.add('is-bouncing-' + dir);
  }

  /* --------------------------------------------------------------- the pack */

  function buildInventory() {
    var slots = ITEMS.map(function (item, i) {
      return '<li><button class="lab-slot" data-item="' + i + '">' +
        '<span class="lab-slot-icon">' + item.icon + '</span>' +
        '<span class="lab-slot-name">' + escapeHtml(item.name) + '</span>' +
        '</button></li>';
    }).join('');

    inventory.innerHTML =
      '<h2 class="lab-inv-title">inventory</h2>' +
      '<ul class="lab-slots">' + slots + '</ul>' +
      '<p class="lab-flavor" id="lab-flavor"></p>';

    flavorLine = inventory.querySelector('#lab-flavor');
  }

  function toggleInventory(open) {
    var show = open === undefined ? inventory.hidden : open;
    inventory.hidden = !show;
    pack.setAttribute('aria-expanded', String(show));
    if (!show && flavorLine) flavorLine.textContent = '';
  }

  /* The rope is the only item that does anything. On the site it hauls you back
     to the start block — the labyrinth is the whole site now, so there is nowhere
     else to be let out to. Inside the editor's test run it does let you out,
     because there the way out is back to the editor. */
  function useItem(i) {
    var item = ITEMS[i];
    if (!item) return;

    if (item.escape && previewing) {
      exitLabyrinth();
      return;
    }
    if (item.escape) returnToStart();

    flavorLine.textContent = item.flavor;
  }

  /* ------------------------------------------------------------- enter/exit */

  /* Never stop on a tunnel: a stale saved block, or a start block someone turned
     into a tunnel, would leave you looking at a transition with nowhere to go.
     With no entry direction nothing is excluded from the pick. */
  function firstChamber(cell) {
    if (!isTunnel(cell)) return cell;

    var route = tunnelRoute(index, cell, null, Math.random);
    return route.dest ||
      index.maze.cells.filter(function (c) { return !isTunnel(c); })[0] ||
      cell;
  }

  function enterLabyrinth(cellId) {
    if (active) return;

    var start = index.byId.get(cellId) || index.byId.get(index.maze.start) || index.maze.cells[0];
    if (!start) return;

    /* read the links now rather than at startup: map.js and this file are both
       injected dynamically, so the map may not have existed yet when init() ran */
    links = buildLinkIndex(index.maze);

    active = true;
    root.hidden = false;
    stage.innerHTML = '';

    showCell(firstChamber(start));
    toggleInventory(false);
  }

  /* Leaves the pack open on purpose, so the rope's line stays up while the block
     behind it changes — closing it would wipe the one bit of feedback you get. */
  function returnToStart() {
    if (!active || moving) return;

    var start = index.byId.get(index.maze.start) || index.maze.cells[0];
    if (!start) return;

    showCell(firstChamber(start), 'up'); /* the rope pulls you up out of it */
  }

  /* Runs an arbitrary map in place, for the editor's test button. Nothing is
     written to sessionStorage, so a test run leaves no trace on the real site. */
  function preview(maze, startId, onExit) {
    if (!root) return false;

    if (active) exitLabyrinth();

    index = indexMaze(maze);
    previewing = true;
    onPreviewExit = onExit || null;
    enterLabyrinth(startId);
    return true;
  }

  /* Only the editor's test run ever ends. On the site there is no outside to
     close the overlay onto, so nothing calls this. */
  function exitLabyrinth() {
    if (!active) return;

    active = false;
    moving = false;
    root.hidden = true;
    stage.innerHTML = '';
    toggleInventory(false);

    var done = onPreviewExit;
    previewing = false;
    onPreviewExit = null;
    if (done) done();
  }

  /* ----------------------------------------------------------------- input */

  /* A paragraph too long for its box scrolls inside it. The stage swallows touch
     gestures wholesale, so a drag that starts in one of those has to be left
     alone or the visitor can never read to the bottom of it — they'd swipe to
     the next block instead. Only counts while there is actually more text than
     fits; a paragraph that isn't overflowing swipes like everything else. */
  function inScrollable(target) {
    var para = target && target.closest && target.closest('.lab-el-para');
    return !!para && para.scrollHeight > para.clientHeight + 1;
  }

  function bindGestures() {
    var startX = 0;
    var startY = 0;
    var tracking = false;
    var swiped = false;

    stage.addEventListener('pointerdown', function (e) {
      tracking = !inScrollable(e.target);
      swiped = false;
      startX = e.clientX;
      startY = e.clientY;
    });

    stage.addEventListener('pointerup', function (e) {
      if (!tracking) return;
      tracking = false;

      var dx = e.clientX - startX;
      var dy = e.clientY - startY;

      if (Math.abs(dx) < SWIPE_THRESHOLD && Math.abs(dy) < SWIPE_THRESHOLD) return;
      swiped = true;

      /* Dragging the page up pulls in whatever sits below it, the same way every
         other endless-scroll app works. Same for the other three. */
      if (Math.abs(dy) >= Math.abs(dx)) {
        move(dy < 0 ? 'down' : 'up');
      } else {
        move(dx < 0 ? 'right' : 'left');
      }
    });

    stage.addEventListener('pointercancel', function () { tracking = false; });

    /* a swipe that started on the link shouldn't open the link */
    stage.addEventListener('click', function (e) {
      if (swiped) {
        e.preventDefault();
        swiped = false;
        return;
      }

      var arrow = e.target.closest('.lab-arrow');
      if (arrow) {
        move(arrow.dataset.dir);
        return;
      }

      var button = e.target.closest('.lab-btn');
      if (!button) return;

      if (button.dataset.random) jumpAnywhere();
      else if (button.dataset.goto) jumpTo(button.dataset.goto);
    });
  }

  function bindKeys() {
    document.addEventListener('keydown', function (e) {
      if (!active) return;

      if (e.key === 'Escape') {
        toggleInventory(false);
        return;
      }
      var dir = { ArrowUp: 'up', ArrowDown: 'down', ArrowLeft: 'left', ArrowRight: 'right' }[e.key];
      if (!dir) return;

      e.preventDefault();
      move(dir);
    });
  }

  /* ------------------------------------------------------------------ setup */

  function init() {
    root = document.getElementById('labyrinth');
    if (!root) return;

    /* The editor hosts this too, for its test button, and marks its container
       data-preview so we don't open the live map on top of the editor. */
    var previewHost = root.hasAttribute('data-preview');

    index = indexMaze(loadMaze());

    root.innerHTML =
      '<div class="lab-stage" id="lab-stage"></div>' +
      '<div class="lab-veil" id="lab-veil"></div>' +
      '<button class="lab-pack" id="lab-pack" aria-expanded="false" aria-label="backpack">🎒</button>' +
      '<div class="lab-inventory" id="lab-inventory" hidden></div>';

    stage = root.querySelector('#lab-stage');
    veil = root.querySelector('#lab-veil');
    pack = root.querySelector('#lab-pack');
    inventory = root.querySelector('#lab-inventory');

    buildInventory();
    bindGestures();
    bindKeys();

    pack.addEventListener('click', function () { toggleInventory(); });

    inventory.addEventListener('click', function (e) {
      var slot = e.target.closest('.lab-slot');
      if (slot) useItem(Number(slot.dataset.item));
    });

    if (previewHost) return;

    /* There is no front door any more — the labyrinth is the site. A reload
       picks up where you were; a fresh tab starts at the beginning. */
    var saved = null;
    try { saved = sessionStorage.getItem(STORAGE_KEY); } catch (err) { /* private mode */ }
    enterLabyrinth(saved);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

  /* used by _tools/labyrinth-editor.html and _tools/maze-check.js */
  var api = {
    indexMaze: indexMaze,
    reachableFrom: reachableFrom,
    encodeMaze: encodeMaze,
    decodeMaze: decodeMaze,
    loadMaze: loadMaze,
    preview: preview,
    isTunnel: isTunnel,
    tunnelRoute: tunnelRoute,
    pickExit: pickExit,
    hasLayout: hasLayout,
    layoutProblems: layoutProblems,
    renderMarkup: renderMarkup,
    markupUrls: markupUrls,
    cellUrls: cellUrls,
    safeUrl: safeUrl,
    escapeHtml: escapeHtml,
    buildElement: buildElement,
    DIRS: DIRS,
    DIR_NAMES: DIR_NAMES,
    OPPOSITE: OPPOSITE,
    EFFECTS: EFFECTS,
    GRID: GRID,
    EL_TYPES: EL_TYPES,
    EL_LIMITS: EL_LIMITS,
    EL_DEFAULTS: EL_DEFAULTS,
    BUTTON_ACTIONS: BUTTON_ACTIONS,
    TUNNEL_DEFAULTS: TUNNEL_DEFAULTS,
    TUNNEL_HOPS: TUNNEL_HOPS
  };
  if (typeof window !== 'undefined') window.Labyrinth = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})();
