/* Labyrinth mode.

   A deliberately bad way to browse the links: one link per page, move between
   pages by swiping up/down/left/right. Only some directions exist from any given
   page, and a few of them lie.

   The map is generated by _tools/labyrinth-editor.html. Don't hand-edit it. */

(function () {
  'use strict';

  var DIRS = { up: [0, -1], down: [0, 1], left: [-1, 0], right: [1, 0] };
  var DIR_NAMES = ['up', 'down', 'left', 'right'];
  var OPPOSITE = { up: 'down', down: 'up', left: 'right', right: 'left' };
  var KEY = 'ariadne';

  /* how many tunnels in a row before we give up and put the visitor somewhere */
  var TUNNEL_HOPS = 12;
  var TUNNEL_DEFAULTS = { color: '#000000', ms: 500, fx: 100, effect: 'fade', back: 0 };
  var EFFECTS = ['fade', 'crossfade', 'slide', 'iris', 'flicker'];

  /* ---------------------------------------------------------------- the map */
  /* --- generated map: replace everything down to "end generated map" --- */
     var labyrinth = {
    start: 'c19',
    cells: [
      { id: 'c0', x: -3, y: 0, link: 'https://ramkalo.github.io/Tunnelinator' },
      { id: 'c1', x: 2, y: 1, tunnel: { color: '#000000', ms: 750, fx: 300, effect: 'crossfade', back: 10 }, exits: { right: null } },
      { id: 'c2', x: 3, y: 1, link: 'https://www.provomusicscene.com/' },
      { id: 'c3', x: 3, y: 2, tunnel: { color: '#000000', ms: 500, fx: 600, effect: 'iris', back: 30 } },
      { id: 'c4', x: 3, y: 3, link: 'https://ramkalo.github.io/bxtrxt', exits: { up: 'c2' } },
      { id: 'c5', x: 4, y: 3, tunnel: { color: '#000000', ms: 1000, fx: 300, effect: 'fade', back: 10 } },
      { id: 'c6', x: 2, y: 3, tunnel: { color: '#000000', ms: 500, fx: 450, effect: 'crossfade', back: 20 } },
      { id: 'c7', x: 5, y: 3, link: 'https://www.punk-website.com/' },
      { id: 'c8', x: 1, y: 3, link: 'https://ramkalo.github.io/Obeyinator' },
      { id: 'c9', x: 3, y: 4, tunnel: { color: '#000000', ms: 500, fx: 300, effect: 'flicker', back: 10 }, exits: { down: null } },
      { id: 'c10', x: 3, y: 5, link: 'https://hadeanlights.bandcamp.com/' },
      { id: 'c11', x: 4, y: 5, link: 'https://www.provomusicscene.com/' },
      { id: 'c12', x: 2, y: 5, link: 'https://justaqrcode.com/' },
      { id: 'c13', x: 3, y: 6, tunnel: { color: '#000000', ms: 750, fx: 300, effect: 'iris', back: 10 } },
      { id: 'c14', x: 3, y: 7, link: 'https://ramkalo.bandcamp.com/', exits: { left: 'c24' } },
      { id: 'c15', x: 0, y: 3, tunnel: { color: '#000000', ms: 500, fx: 600, effect: 'fade', back: 30 } },
      { id: 'c16', x: -1, y: 3, tunnel: { color: '#000000', ms: 750, fx: 150, effect: 'crossfade', back: 0 } },
      { id: 'c17', x: -2, y: 3, link: 'https://ramkalo.github.io/Obeyinator' },
      { id: 'c18', x: -2, y: 4, tunnel: { color: '#000000', ms: 500, fx: 450, effect: 'iris', back: 20 } },
      { id: 'c19', x: -2, y: 5, link: 'https://hadeanlights.bandcamp.com/', exits: { right: 'c35' } },
      { id: 'c20', x: -1, y: 5, tunnel: { color: '#000000', ms: 1000, fx: 150, effect: 'fade', back: 0 } },
      { id: 'c21', x: -1, y: 7, tunnel: { color: '#000000', ms: 500, fx: 300, effect: 'crossfade', back: 10 } },
      { id: 'c22', x: 2, y: 7, tunnel: { color: '#000000', ms: 750, fx: 450, effect: 'slide', back: 20 } },
      { id: 'c23', x: 1, y: 5, tunnel: { color: '#000000', ms: 1000, fx: 600, effect: 'iris', back: 30 } },
      { id: 'c24', x: -3, y: 1, tunnel: { color: '#000000', ms: 500, fx: 150, effect: 'flicker', back: 0 }, exits: { up: null } },
      { id: 'c25', x: -3, y: -1, link: 'https://www.punk-website.com/' },
      { id: 'c26', x: -4, y: 0, link: 'https://ramkalo.github.io/Obeyinator' },
      { id: 'c27', x: -2, y: 0, link: 'https://ramkalo.github.io/Tunnelinator' },
      { id: 'c28', x: -3, y: 2, link: 'https://hadeanlights.bandcamp.com/' },
      { id: 'c29', x: -4, y: 2, tunnel: { color: '#000000', ms: 1000, fx: 300, effect: 'flicker', back: 10 }, exits: { down: 'c19' } },
      { id: 'c30', x: -5, y: 2, link: 'https://justaqrcode.com/' },
      { id: 'c31', x: -5, y: 1, tunnel: { color: '#000000', ms: 750, fx: 600, effect: 'crossfade', back: 30 } },
      { id: 'c32', x: -6, y: 2, tunnel: { color: '#000000', ms: 1000, fx: 150, effect: 'slide', back: 0 } },
      { id: 'c33', x: -5, y: 3, tunnel: { color: '#000000', ms: 500, fx: 300, effect: 'iris', back: 10 } },
      { id: 'c34', x: -5, y: 0, link: 'https://www.punk-website.com/', exits: { left: 'c30' } },
      { id: 'c35', x: -7, y: 2, link: 'https://ramkalo.github.io/Obeyinator' },
      { id: 'c36', x: -5, y: 4, link: 'https://ramkalo.github.io/Tunnelinator' },
      { id: 'c37', x: 1, y: 1, link: 'https://hadeanlights.bandcamp.com/' }
    ]
  };

  /* Prebuilt cache of the map above. Falls back to it if anything goes wrong. */
  var LABYRINTH_CACHE =
    'GlAaFQUcEUNISwJXWUdNUAoECAIWQ0gyGkYHAUNISwJUTElDCktbSV1JQwtLW1RCRxUbHQ0BTF9DJSwtJyEo' +
    'JFBFQwoBEQRQU0MqAQsEUgYHRBoNCAFJCBdOLAUXCA1GE0kaUAAFRlRHAkNLTUYWR1tARUMdTF9QXksVEQAL' +
    'BB5LWx9MBg4eBhNGVEdCQllRVF5VQ15LDBdMX1NCWVFITAAHFAwCEExfQxQIBQFMSUMQCAIPTF9RXksWAQcC' +
    'CQYaQ14VRw0XDxVGVFRNUBsIAwYRQ0hYHEhMAxlQU1RUXhhNUB0IEAIAQ0hLJQUcDg8XGhJGQkcPHR0ERlRH' +
    'OB0cQRcaEAwQBQREGg0THRwGDE4EQRYIEw9OFQABGgADC0UWExBPRDcKFABJFgUAAQQAAA8DTg0AHA0SRAgM' +
    'DxZJAEQeDAQRDEELCEURExkEFk4SCRsKCUQXChRSGgkLGABBGwcVC04cDgcbQQYPAkEQDAcLHABBEQYPEAcL' +
    'FBsHBkpMGE0JSwgATF9DEVtDSEwdQ0haTUYXR1tDRUMKAREEUFNDAwEKBVIDDgZCRRgdHEEJDwEEUgAVRBoN' +
    'Ex0cBgxOBEEGHA8KCwlBGwcVC04RCRdJDwEWEUERAQAJDAATXEkvCxlFBh1JBBweCQ4ADE9EJ0INHkkDAU4N' +
    'BAAMQRMPDBUbBwZKTiwHUhAOEU4LBBcNQRABRQ0XCBcBThEJFwdBBwYAAhlJGAsbF0EQCAIPHgQCGUVBFAsX' +
    'CRMZEkQXChRSAQASC0URGwoKAQpFFAJJEgsDABUaAA8DThASFw8UCEBHTVAdCBACAENISw8NDQBAUBRNH0wM' +
    'BVBTQwddR01QEUNeXUlDC0tbVkJHFQcHDwECR1sJSwILAgoTUFNDR15VUUJZUUZCRwwBS1tRXlVNUA8ZRlRU' +
    'UUJFQwEIAwQRHUNeTAMAFgxDSEwHABECQ15eSUMFDAgDBhESUFMaRhsVQ0hYTUYKChYcS1tVExhNUAcOEAtH' +
    'W1AQDhFOFg0bDQRECgoWHEkIChoKQRNJEgkPCQ1SCgkFAwcEAEscSBVHCBZLW0YNUUNeSxlGVFZNUBBDXl1J' +
    'Qx4ADw9MX0MaHRUUHV9OXR4WE0AMDwEdAAMcBAxcCg4JQRcAHwIACAEIFAEAAktMSUMcBhUBTF9DWhkSFx0R' +
    'FQZHT0pOPA4HSQIFAEUCHgACD04RCRdJAw0JRQYADAQKTgkEBh0EFh1FFR1JFw0dDBVSHQkBThIEEBoIEAtM' +
    'Qw9FGkYHAUNISwJRTElDCktbUEJHGFBTUkhMERQcBwQITF8aUAoOCAEXQ0hLQlReVVFCWUNITAgSUFNQUV5V' +
    'TVAPGUZUVFFCRUMBCAMEER1DXkwDABYMQ0hMBwARAkNeXklDBQwIAwYRElBTGkYCAAcGS1tVQkcTGw4JEExf' +
    'UA8UTUYAChUXS1tGD0UCEwUMRB0KFBwNQQEAEQQAGkEdARATUgwAFk4HAB4FEkZCRxUbHQ0BTF9DCwYUQxgA' +
    'QRAMBApODQQADEEGCwMOAAxPSkBFDBMQAwFRRxxeEkMNCkdbUApXRkJHGVBTU0hMHENIWk1GGhAPHAwNRlQe' +
    'QxEGDQscR1tQSlFUXlVRQktNRgMWQ0heVFRCRwcKS1tVXlVNUAwHAgsGFVBTQwIPAQRQRUMGDwYKUFNRSEwS' +
    'BBsOCRAdR1sJSw0BCBFDSFhNRhwMBhodQ15fGBxeSw8LGgBDSEsMER0MAlIZDQUXFkEbB0EQBgBBFgASEA8L' +
    'AhdLTUYaDBUeDENeTAAEAAAERAYEDR4eAB1MGE0JSwgATF9DEV5DSEwdQ0hcTUYXR1tBRUMIBwsKUFNDDBoR' +
    'EQFTTksGBAUXCA8IBwIJBhpPBg8LBREIDBRABg4fRkMZQh5DGw1DXkwGWVBFQxxMX1BeSxhGVFZNUAUICgVH' +
    'W1ABFRAeFltdRhMFAw4AHgZPBg8LBREIDBRABg4fRkMZQh5DGw1DXkwGWFBFQxxMX1JeSxhGVFFNUB0UCgAA' +
    'DVBTGkYNCg0dG0NeTEZRQllRVF5HTVAEEkZUUlRCRUMCFkdbR1lNRgsDBxcKFUZURwcTDQRGQkcDEwoKRlRV' +
    'TVAeBA0JDRUBS1sfTBARUFNQSEwBDgUHQ15fGBxeSw8LGgBDSEsYCxtFCRcIE0QIBAgcHUEHAgwCGQAPA04K' +
    'B1IIQQ8LHAMdCBMATElDBgAVCAtHW1A8EUQPRTIGCAgWDQQSF0scSBVHCBZLW0YNVFFQRUMcTF9SXksYRlRQ' +
    'TVAFCAoFR1tQARUQHhZbXUYTBQMOAB4GTwMHEQkHC08NAUo1BwcPAQIMDxMdDhZMGE0JSwgATF9DEVhQRkJH' +
    'GVBTVUhMHENIXE1GAgwPGUtbRgYRFQIaW0tBFwAfAgAIAUsGGx0JEQxLCB1GAxwaFxkGSxxIFUcIFktbRg1U' +
    'U1BFQxxMX1NeSxhGVFBNUAUICgVHW1ABFRAeFltdRhMFAw4AHgZPAwcRCQcLTw0BSi4QDBgNAAQVHRtDGUIe' +
    'QxsNQ15MBlBBS01GFkdbQUVDHUxfV15LFREACwQeS1sfTAYOHgYTRlRHQkJZUVReVUNeSwwXTF9WR1lNRggd' +
    'Q0hcUUhMAAcUDAIQTF9DFAgFAUxJQxAIAg9MX1FeSxYBBwIJBhpDXhVHFAJLW1VCRwUdHg9GVFQcDxRNH0wM' +
    'BVBTQwdfUUNeSxlGVFZNUBBDXllJQx4ADw9MX0MaHRUUHV9OXQMUFxoEEAAKDgALSwIdBE5GE0kaUAAFRlRH' +
    'AkNcQ0hMHUNIWU1GF0dbQUVDEBsLDxcFQ14VRwIdBQ4WTF9DUVlRVF5VUVBFQwkdR1tDWVFUQkcHCktbUV5J' +
    'QxcPBwENEUNISwcFCgBDXksDBQ0OQ0hZTUYZAAgVARUXTF8aUAUEAhpHW0NFQxYHAgkGS1tVExhNUB0IEAIA' +
    'Q0hLIgUcAAcHBUBGQkcPHR0ERlRHJR0HRhBOAgQGSQ0LHRFDD0UaRgcBQ0hLAlVYR01QEUNeQ1RNUBBDXl1J' +
    'QwYcDwoLCUNIEkMHAQkOAEtbRk1VUUJZUVRMSUMfGkNeX1VRQkVDAhZHW0dZTUYLAwcXChVGVEcHEw0ERkJH' +
    'AxMKCkZUVU1QHgQNCQ0VAUtbH0wJBBQdQ15fSUMAAAYMGkdbQxQcSEwRCAYFBEZURzUFBkEwGwsPFwUSW0xJ' +
    'QxwGFQFMX0MmHg5EBwtBE0kTCxlaQw9FGkYHAUNISwJVWUdNUBFDXkNXTVAQQ15dSUMeAA8PTF9DGh0VFB1f' +
    'Tl0eFhNAFRQcAkwTCwcSGx0ESg0KDF1LHEgVRwgWS1tGDVRZUEVDHExfTEBFQx1MX1VeSxURAAsEHktbH0wG' +
    'Dh4GE0ZUR0JCWVFUXlVDXksMF0xfUEJZUUhMAxlQU1RUQkcEFA8EBxpHW1APAAALR01QCwAHBUdbQkVDEwsM' +
    'BhodEkZUHkMHGUNeX0lDFgYWCkxfUA8UTUYaDBUeDENeTDEJEx1BEw8WQRNJFgEHFwVSHgQGHQwVF0scSBVH' +
    'CBZLW0YNVFhQRUMcTF9MQEVDHUxfVF5LDQ0ADkNISwkQGhUSSEZOExkSTwIbDhIBCBQBAAIXDQAPF0cCCwNK' +
    'Qw9FGkYHAUNISwJWXkdNUBFDXkNUTVAQQ15bSUMGHA8KCwlDSBJDBwEJDgBLW0ZNVVFCWVFUTElDHxpDXlxV' +
    'UUJFQwIWR1tHWVFITAAHFAwCEExfQxQFCAcFABNQRUMGDwYKUFNRSEwSBBsOCRAdR1sJSw0BCBFDSFgcGUJH' +
    'FRsdDQFMX0MrBhREHQ0OBwUFCkkRQRAMQQwLFwRcS01GCx0IBhpDXhVHExsOCRBMX0MRW1BGExhNCUsIAExf' +
    'QxFbUEZCRxlQU0xVQkcYUFNWSEwRFBwHBAhMXxpQCg4IARdDSEtCVF5VUUJZQ0hMCBJQU1BUXlVNUA8ZRlRQ' +
    'UUJFQwEIAwQRHUNeTAMAFgxDSEwHABECQ15eSUMFDAgDBhESUFMaRhwMBhodQ15fGBxeSxUNGgkEUFNDKCsk' +
    'NzdIQSohMkBQRUMBFgwVAUtbH0wXCBUBFUZURwJCSxwZQh5DGw1DXkwGU0BLTUYWR1tARUMdTF9WXksVEQAL' +
    'BB5LWx9MBg4eBhNGVEdCQllRVF5VQ15LDBdMX1NCWVFITAMZUFNQVF5JQxcPBwENEUNISxIIBwEEUEVDBg8G' +
    'ClBTUUhMEgQbDgkQHUdbCUsNAQgRQ0hYTUYcDAYaHUNeXxgcXksEHAcRElBTGkYCAAcGS1tGDVJDD0VDCgER' +
    'BFBTQxAGAEETABNEGQoOAQEEF04EEx0cDwBOHA4HSQAKCkUYHRxBAgsADVIaCAcFRxxeEkMNCkdbUApTV0xJ' +
    'QwpLW1VCRxhQU1RITBEUHAcECExfGlAKDggBF0NIS0JUXlVRQllDSEwIElBTUFFeVU1QDxlGVFBRQkVDAQgD' +
    'BBEdQ15MBhMdGhICDwEEUEVDBg8GClBTUUhMEgQbDgkQHUdbCUsTDQkNFVBTUBkTSUMXEQgQHUdbCUsTDQkN' +
    'FVBTQwdWRxxeSw8LGgBDSEs4CxtFBxMFDUQHCxUdSQBEHgwVUggPAE4HExcICkQaDRMdHAYMThYEBAwTBQJF' +
    'Bx4GDhYdRxxeEkMNCkdbUApTUExJQwpLW0ldSUMLS1tVQkcVBwcPAQJHWwlLAgsCChNQU0NHXlVRQllRRkJH' +
    'DAFLW1VeVVFeSwccTF9QQllNRgsDBxcKFUZURwcTDQRGQkcDEwoKRlRVTVAeBA0JDRUBS1sfTBARUFNQSEwB' +
    'DgUHQ15fGBxeSw8LGgBDSEsoQwNFEh0bEx1OLEEeDAVEFwoUUgEEFgtHHF4SQw0KR1tQClNRTElDCktbSV1J' +
    'QwtLW0lfSUMcBhUBTF9DGx0SRA8LQRcEERAXRRMdBgxGE0kaUAAFRlRHAkBfQ0hMHUNIRFVITBxDSFlNRgAK' +
    'FRdLW0YHERJSCA9ECwgRBhBBFgEKDFBFQwEWDBUBS1sfTAkEFB1DXgAQDR4UHEgVRwgWS1tGDVdWUEVDHExf' +
    'TEBFQx1MX1FeSw8LGgBDSEsIEB1FABxJBAkeERhSGw4LA0ccXhJDDQpHW1AKU1xMSUMKS1tJXUlDC0tbVkJH' +
    'Dx0dBEZURwgGGkEFThcOHQRNRA8LBVIAFRdOAAwCHRhGE0kaUAAFRlRHAkBQQ0hMHUNIRFVITBxDSFtNRhoQ' +
    'DxwMDUZUHkMRBg0LHEdbUEpRVF5VUUJLTUYDFkNIWFFUXklDFBFDXl9VUV5LBAIIAAIGS1tGCAQFF0tNRgwE' +
    'AhlLW1RCRxYXAAYMGhZDSBJDCAsDFVBTUEhMFwgVARVGVFQcD0VDCgERBFBTQy1OAQ4cThVEGg0IHAJBEAYA' +
    'GFIeCAgCRQ0XHUEJC0UNFx1BHQEQQRUGQQoBEkMPRRpGBwFDSEsCV15HTVARQ15DUE1QEENeXElDHAYVAUxf' +
    'QxNJEwsBCE9SIBVDHUUPHR1BAQMVFQtHQ0hMABkbHRJGVB5DAAAGDBpHWxwcDQgTGE0JSwgATF9DEVpQRkJH' +
    'GVBTTFFCRxhQU1BITBEUHAcECExfGlAKDggBF0NIS0JUXlVRQllDSEwIElBTUFReVU1QDxlGVFRRQkVDAQgD' +
    'BBEdQ15MAwAWDENITAcAEQJDXl5JQwUMCAMGERJQUxpGGxVDSFhNRgoKFhxLW1UTGE1QBw4QC0dbUBkNAQ8W' +
    'BFIaFQseRRMHBw8NAAJPUBRNH0wMBVBTQwddV0NeSxlGVEhXXksYRlRXTVAdFAoAAA1QUxpGDQoNHRtDXkxG' +
    'UUJZUVReR01QBBJGVFRRQllNRggdQ0hYUVRCRwQUDwQHGkdbUA8AAAtHTVALAAcFR1tCRUMTCwwGGh0SRlQe' +
    'Qx4MBxBMX1BeSxMNCQ0VUFNQGRNJQxwGFQFMX0MCBQQFHQBBAR0OFE4XFBwHCAoJS0ErBhRDHABBEwUTAQ8B' +
    'GFIdDgtOAQQXGU9GE0kaUAAFRlRHAkFaQ0hMHUNIRFRITBxDSFpNRhoQDxwMDUZUHkMRBg0LHEdbUEpRVF5V' +
    'UUJLTUYDFkNIWFFUXklDFBFDXl9VUV5LBAIIAAIGS1tGCAQFF0tNRgwEAhlLW1RCRxYXAAYMGhZDSBJDER5H' +
    'W0NFQwABEg9QU1AZE0lDHAYVAUxfQztJCQUYAEEGBkEJDw4EUhAOEU4WFR0ZQRYbCw8bBwZEAAoWXEkoQwNF' +
    'Eh0bEx1ARxxeEkMNCkdbUApSUExJQwpLW0lbSUMLS1tUQkcECgAVF0xfGlAbCAMGEUNIBxQIAhhNUAcOEAtH' +
    'W1AwDhFJFwRSHRMFHhUEFkkPCxlLQTgcEhBOFggGR0EtGkUWGwUNRAwAQR0CAB1ARxxeEkMNCkdbUApSUUxJ' +
    'QwpLW0lZSUMLS1tWQkcPHR0ERlRHOB0cRggCRQMXSQkBHABBHAYWSk4sFVUaQQsFBBhcSxxIFUcIFktbRg1W' +
    'V1BFQxxMX0xHRUMdTF9VXksEHAcRElBTGkYbFUNIBxQIAhhNUAcOEAtHW1AwDhFJFwRSHRMFHhUEFkkPCxlL' +
    'QSUBGEQKDAUcThVEFwoUUgMUFxpFEgYGEUQcEA8cAA8DQEccXhJDDQpHW1AKUlNMSUMKS1tVQkcYUFNQSEwL' +
    'DgYMQ15MPA4HSQcLGwsFUh0JAU4JABAQEw0AEQlcSTgLG0UCEwdBCg8TCBUIFQFOBxhSGhYNHgwPFUkOFk4H' +
    'GFIcEg0AAkEGAQREDxcTHR5BDwscElIGD0QPRQoXEAMLDxcFXEk1DAsXBFIIEwFOBA0BBkEIBxEVHgxBBRwX' +
    'DgUaQQsARRUaDEEXDRcEFwdBHQEQQREID0QNCQgRAkEGGxFBBgEAEEkWQRwGFUQHAQQTBU9EAAoPF0kOAk4R' +
    'CRsaQQ0dRQgWDAAIQEdNUB0IEAIAQ0hLNgECBg4fDEMZMxg=';
  /* --- end generated map --- */

  function decodeMaze(blob) {
    var bin = atob(blob);
    var bytes = new Uint8Array(bin.length);
    for (var i = 0; i < bin.length; i++) {
      bytes[i] = bin.charCodeAt(i) ^ KEY.charCodeAt(i % KEY.length);
    }
    return JSON.parse(new TextDecoder().decode(bytes));
  }

  function encodeMaze(maze) {
    var bytes = new TextEncoder().encode(JSON.stringify(maze));
    var bin = '';
    for (var i = 0; i < bytes.length; i++) {
      bin += String.fromCharCode(bytes[i] ^ KEY.charCodeAt(i % KEY.length));
    }
    return btoa(bin);
  }

  function loadMaze() {
    try {
      return decodeMaze(LABYRINTH_CACHE);
    } catch (err) {
      return labyrinth;
    }
  }

  /* ------------------------------------------------------------ maze lookup */

  /* Wraps a maze in id/coordinate lookups plus the one movement rule everything
     else defers to. The editor and _tools/maze-check.js call this too, so the
     three can never disagree about where a swipe leads. */
  function indexMaze(maze) {
    var byId = new Map();
    var byXY = new Map();

    maze.cells.forEach(function (cell) {
      byId.set(cell.id, cell);
      byXY.set(cell.x + ',' + cell.y, cell);
    });

    return {
      maze: maze,
      byId: byId,
      byXY: byXY,

      /* 1. an explicit exit id wins  -> wormhole, can land anywhere
         2. an explicit null          -> hard wall
         3. otherwise                 -> the neighbouring square, if one exists */
      resolveExit: function (cell, dir) {
        if (cell.exits && Object.prototype.hasOwnProperty.call(cell.exits, dir)) {
          var target = cell.exits[dir];
          return target ? byId.get(target) || null : null;
        }
        var step = DIRS[dir];
        return byXY.get((cell.x + step[0]) + ',' + (cell.y + step[1])) || null;
      }
    };
  }

  function reachableFrom(index, startId) {
    var start = index.byId.get(startId) || index.maze.cells[0];
    if (!start) return new Set();

    var seen = new Set([start.id]);
    var queue = [start];

    while (queue.length) {
      var cell = queue.shift();
      DIR_NAMES.forEach(function (dir) {
        var next = index.resolveExit(cell, dir);
        if (next && !seen.has(next.id)) {
          seen.add(next.id);
          queue.push(next);
        }
      });
    }
    return seen;
  }

  /* ---------------------------------------------------------------- tunnels */

  /* A tunnel is a block you pass through rather than stop in. It shows its
     message for a moment, then hands you to one of its neighbours at random. */
  function isTunnel(cell) {
    return !!(cell && cell.tunnel);
  }

  /* Pale tunnel colors need dark text or the message disappears. */
  function isLight(color) {
    var hex = String(color || '').replace('#', '');
    if (hex.length === 3) hex = hex[0] + hex[0] + hex[1] + hex[1] + hex[2] + hex[2];
    if (!/^[0-9a-f]{6}$/i.test(hex)) return false;

    var r = parseInt(hex.slice(0, 2), 16);
    var g = parseInt(hex.slice(2, 4), 16);
    var b = parseInt(hex.slice(4, 6), 16);
    return (r * 0.299 + g * 0.587 + b * 0.114) > 150;
  }

  function tunnelSetting(cell, key) {
    var conf = cell.tunnel || {};
    return conf[key] === undefined || conf[key] === null ? TUNNEL_DEFAULTS[key] : conf[key];
  }

  /* Weighted pick among the neighbours a tunnel actually has.
     `entryDir` is the direction you were travelling when you arrived, so the way
     back out is the opposite of it — weighted by `back`, which defaults to 0. */
  function pickExit(index, cell, entryDir, rng) {
    var exits = [];
    DIR_NAMES.forEach(function (dir) {
      var next = index.resolveExit(cell, dir);
      if (next) exits.push({ dir: dir, cell: next });
    });
    if (!exits.length) return null;

    var backDir = entryDir ? OPPOSITE[entryDir] : null;
    var weights = (cell.tunnel || {}).weights || {};

    var forward = exits.filter(function (e) { return e.dir !== backDir; });
    var back = exits.filter(function (e) { return e.dir === backDir; })[0];

    var pool = forward.map(function (e) {
      var w = weights[e.dir];
      return { exit: e, weight: typeof w === 'number' && w >= 0 ? w : 1 };
    });
    if (back) pool.push({ exit: back, weight: Math.max(0, tunnelSetting(cell, 'back')) });

    var total = pool.reduce(function (sum, p) { return sum + p.weight; }, 0);

    /* Everything weighted to zero. Split evenly among the ways onward, and only
       hand them back the way they came if there is no other way at all. */
    if (total <= 0) {
      var evens = forward.length ? forward : (back ? [back] : []);
      if (!evens.length) return null;
      return evens[Math.min(evens.length - 1, Math.floor(rng() * evens.length))];
    }

    var roll = rng() * total;
    for (var i = 0; i < pool.length; i++) {
      roll -= pool[i].weight;
      if (roll < 0) return pool[i].exit;
    }
    return pool[pool.length - 1].exit;
  }

  /* Walks a run of tunnels to the chamber on the far side. Safe to call on any
     block: a chamber returns itself with an empty path. `dest` comes back null
     only if the tunnels never reach a chamber, which the caller treats as "stay
     where you were" rather than stranding anyone. */
  function tunnelRoute(index, cell, entryDir, rng) {
    var random = rng || Math.random;
    var path = [];
    var dirs = []; /* dirs[i] is the way you leave path[i] */
    var at = cell;
    var dir = entryDir || null;

    for (var hop = 0; hop < TUNNEL_HOPS && isTunnel(at); hop++) {
      path.push(at);

      var pick = pickExit(index, at, dir, random);
      if (!pick) break;

      dirs.push(pick.dir);
      at = pick.cell;
      dir = pick.dir;
    }

    return { path: path, dirs: dirs, dest: isTunnel(at) ? null : at, dir: dir };
  }

  /* --------------------------------------------------------------- contents */

  /* Cells point at a link by url, so editing a link in script.js updates the
     maze too. A cell can override the title or add a note on top of that. */
  function buildLinkIndex() {
    var links = new Map();
    if (typeof data === 'undefined' || !data.categories) return links;

    data.categories.forEach(function (category) {
      (category.links || []).forEach(function (link) {
        links.set(link.url, link);
      });
    });
    return links;
  }

  /* A cell with no link at all is a text-only page — somewhere to put a line of
     nonsense with nothing to click. */
  function cellContent(cell, links) {
    var link = links.get(cell.link) || {};
    var url = cell.link || link.url || '';
    return {
      url: url,
      /* a tunnel with nothing written on it is just a colored flash, not a "???" */
      title: cell.title || link.title || url || (isTunnel(cell) ? '' : '???'),
      description: cell.description || link.description || '',
      note: cell.note || ''
    };
  }

  /* ---------------------------------------------------------------- the pack */

  var ITEMS = [
    { icon: '🪢', name: 'escape rope', escape: true, flavor: 'you know how to use this one.' },
    { icon: '🗝', name: 'bent key', flavor: "it doesn't fit anything here." },
    { icon: '🔋', name: 'dead battery', flavor: 'no charge. you keep it anyway.' },
    { icon: '🗺', name: 'half a map', flavor: 'the useful half is missing.' },
    { icon: '🧾', name: 'a receipt', flavor: 'for something you do not remember buying.' }
  ];

  /* ------------------------------------------------------------------ state */

  var STORAGE_KEY = 'labyrinth-cell';
  var SWIPE_THRESHOLD = 50;

  var index = null;
  var links = null;
  var current = null;
  var active = false;
  var moving = false;
  var previewing = false;  /* running inside the editor's test button */
  var onPreviewExit = null;

  var root, stage, veil, pack, inventory, flavorLine;

  /* ------------------------------------------------------------- rendering */

  function buildPage(cell) {
    var content = cellContent(cell, links);
    var page = document.createElement('article');
    page.className = 'lab-page';

    /* A tunnel gives you no say in where you go, so it gets no arrows. */
    var arrows = isTunnel(cell) ? '' : DIR_NAMES.filter(function (dir) {
      return !!index.resolveExit(cell, dir);
    }).map(function (dir) {
      return '<button class="lab-arrow lab-arrow-' + dir + '" data-dir="' + dir +
        '" aria-label="go ' + dir + '"></button>';
    }).join('');

    if (isTunnel(cell)) {
      var color = tunnelSetting(cell, 'color');
      page.classList.add('lab-tunnel');
      page.style.background = color;
      if (isLight(color)) page.classList.add('is-light');
    }

    var inner =
      '<span class="lab-title">' + escapeHtml(content.title) + '</span>' +
      (content.description ? '<span class="lab-desc">' + escapeHtml(content.description) + '</span>' : '');

    var body = content.url
      ? '<a class="lab-link" href="' + escapeHtml(content.url) + '" target="_blank" rel="noopener noreferrer">' + inner + '</a>'
      : '<div class="lab-link lab-text">' + inner + '</div>';

    page.innerHTML =
      '<div class="lab-page-inner">' + body +
        (content.note ? '<p class="lab-note">' + escapeHtml(content.note) + '</p>' : '') +
      '</div>' + arrows;

    return page;
  }

  var ENTER = { up: 'translateY(-100%)', down: 'translateY(100%)', left: 'translateX(-100%)', right: 'translateX(100%)' };
  var LEAVE = { up: 'translateY(100%)', down: 'translateY(-100%)', left: 'translateX(100%)', right: 'translateX(-100%)' };

  function showCell(cell, dir) {
    var old = stage.querySelector('.lab-page');
    var page = buildPage(cell);

    current = cell;
    remember(cell);

    if (!old) {
      stage.appendChild(page);
      return;
    }

    moving = true;
    page.style.transform = ENTER[dir];
    stage.appendChild(page);

    /* two frames: one to get the start transform committed, one to animate off it */
    requestAnimationFrame(function () {
      requestAnimationFrame(function () {
        old.classList.add('is-leaving');
        old.style.transform = LEAVE[dir];
        page.style.transform = '';
      });
    });

    setTimeout(function () {
      old.remove();
      moving = false;
    }, 360);
  }

  /* ------------------------------------------------------ tunnel transitions */

  /* Swaps in `page` using one of the five effects, then calls done().
     fade and iris drive the veil; the rest animate the pages themselves. */
  function present(page, effect, dir, ms, done) {
    var old = stage.querySelector('.lab-page');
    var half = Math.max(1, Math.round(ms / 2));

    function land() {
      if (old) old.remove();
      done();
    }

    if (effect === 'fade' || effect === 'iris') {
      veil.className = 'lab-veil is-' + effect;
      veil.style.transitionDuration = half + 'ms';

      requestAnimationFrame(function () {
        veil.classList.add('is-closed');

        setTimeout(function () {
          if (old) old.remove();
          stage.appendChild(page);
          veil.classList.remove('is-closed');
          setTimeout(function () {
            veil.className = 'lab-veil';
            done();
          }, half);
        }, half);
      });
      return;
    }

    if (effect === 'slide') {
      page.style.transform = ENTER[dir] || ENTER.down;
      page.style.transition = 'transform ' + ms + 'ms ease';
      stage.appendChild(page);

      requestAnimationFrame(function () {
        requestAnimationFrame(function () {
          if (old) {
            old.style.transition = 'transform ' + ms + 'ms ease';
            old.style.transform = LEAVE[dir] || LEAVE.down;
          }
          page.style.transform = '';
        });
      });
      setTimeout(land, ms);
      return;
    }

    if (effect === 'flicker') {
      page.style.animation = 'lab-flicker ' + ms + 'ms steps(1, end)';
      stage.appendChild(page);
      setTimeout(function () {
        page.style.animation = '';
        land();
      }, ms);
      return;
    }

    /* crossfade, and the fallback for anything unrecognised */
    page.style.opacity = '0';
    page.style.transition = 'opacity ' + ms + 'ms ease';
    stage.appendChild(page);

    requestAnimationFrame(function () {
      requestAnimationFrame(function () { page.style.opacity = '1'; });
    });
    setTimeout(function () {
      page.style.transition = '';
      page.style.opacity = '';
      land();
    }, ms);
  }

  /* Two independent settings. `fx` is how long a transition takes, played once
     on the way in and once on the way out; `ms` is how long the tunnel sits
     there in between. Door to door a tunnel costs fx + ms + fx. */
  function tunnelTiming(cell) {
    return {
      edge: Math.max(0, Number(tunnelSetting(cell, 'fx')) || 0),
      hold: Math.max(0, Number(tunnelSetting(cell, 'ms')) || 0)
    };
  }

  /* Walks the route a tunnel leads to, playing each one in turn. Entering a
     tunnel uses that tunnel's effect; the last one owns the hand-off into the
     chamber on the far side. */
  function playTunnel(tunnel, dir) {
    var route = tunnelRoute(index, tunnel, dir, Math.random);
    var dest = route.dest || current; /* nothing but tunnels — put them back */

    moving = true;

    function finish() {
      current = dest;
      remember(dest);
      moving = false;
    }

    /* Tunnel i is on screen. Hold it, then transition out into whatever is next
       — which is what puts tunnel i+1 on screen, so that one goes straight to
       its own hold rather than being presented twice. */
    function hold(i) {
      var cell = route.path[i];
      var timing = tunnelTiming(cell);
      var effect = tunnelSetting(cell, 'effect');
      var last = i === route.path.length - 1;
      var onward = route.dirs[i] || dir;

      setTimeout(function () {
        present(buildPage(last ? dest : route.path[i + 1]), effect, onward, timing.edge, function () {
          if (last) finish();
          else hold(i + 1);
        });
      }, timing.hold);
    }

    if (!route.path.length) {
      finish();
      return;
    }

    var first = route.path[0];
    present(buildPage(first), tunnelSetting(first, 'effect'), dir, tunnelTiming(first).edge, function () {
      hold(0);
    });
  }

  function remember(cell) {
    if (previewing) return; /* a test run shouldn't move the real visitor's bookmark */
    try { sessionStorage.setItem(STORAGE_KEY, cell.id); } catch (err) { /* private mode */ }
  }

  function travelTo(next, dir) {
    if (isTunnel(next)) playTunnel(next, dir);
    else showCell(next, dir);
  }

  function move(dir) {
    if (!active || moving) return;

    var next = index.resolveExit(current, dir);
    if (!next) {
      bounce(dir);
      return;
    }
    travelTo(next, dir);
  }

  function bounce(dir) {
    var page = stage.querySelector('.lab-page');
    if (!page) return;

    page.classList.remove('is-bouncing-up', 'is-bouncing-down', 'is-bouncing-left', 'is-bouncing-right');
    void page.offsetWidth; /* restart the animation */
    page.classList.add('is-bouncing-' + dir);
  }

  /* --------------------------------------------------------------- the pack */

  function buildInventory() {
    var slots = ITEMS.map(function (item, i) {
      return '<li><button class="lab-slot" data-item="' + i + '">' +
        '<span class="lab-slot-icon">' + item.icon + '</span>' +
        '<span class="lab-slot-name">' + escapeHtml(item.name) + '</span>' +
        '</button></li>';
    }).join('');

    inventory.innerHTML =
      '<h2 class="lab-inv-title">inventory</h2>' +
      '<ul class="lab-slots">' + slots + '</ul>' +
      '<p class="lab-flavor" id="lab-flavor"></p>';

    flavorLine = inventory.querySelector('#lab-flavor');
  }

  function toggleInventory(open) {
    var show = open === undefined ? inventory.hidden : open;
    inventory.hidden = !show;
    pack.setAttribute('aria-expanded', String(show));
    if (!show && flavorLine) flavorLine.textContent = '';
  }

  function useItem(i) {
    var item = ITEMS[i];
    if (!item) return;

    if (item.escape) {
      exitLabyrinth();
      return;
    }
    flavorLine.textContent = item.flavor;
  }

  /* ------------------------------------------------------------- enter/exit */

  function enterLabyrinth(cellId) {
    if (active) return;

    var start = index.byId.get(cellId) || index.byId.get(index.maze.start) || index.maze.cells[0];
    if (!start) return;

    /* read the links now rather than at startup: script.js and this file are both
       injected dynamically, so `data` may not have existed yet when init() ran */
    links = buildLinkIndex();

    active = true;
    root.hidden = false;
    document.body.classList.add('labyrinth-active');
    stage.innerHTML = '';

    /* Never open on a tunnel — a stale saved block or a start block someone made
       a tunnel would leave you looking at a transition with nowhere to go. With
       no entry direction nothing is excluded from the pick. */
    if (isTunnel(start)) {
      var route = tunnelRoute(index, start, null, Math.random);
      start = route.dest || index.maze.cells.filter(function (c) { return !isTunnel(c); })[0] || start;
    }

    showCell(start);
    toggleInventory(false);

    if (!previewing && location.hash !== '#labyrinth') location.hash = 'labyrinth';
  }

  /* Runs an arbitrary map in place, for the editor's test button. Nothing is
     written to the address bar or to sessionStorage, so a test run leaves no
     trace on the real site. */
  function preview(maze, startId, onExit) {
    if (!root) return false;

    if (active) exitLabyrinth();

    index = indexMaze(maze);
    previewing = true;
    onPreviewExit = onExit || null;
    enterLabyrinth(startId);
    return true;
  }

  function exitLabyrinth() {
    if (!active) return;

    active = false;
    moving = false;
    root.hidden = true;
    document.body.classList.remove('labyrinth-active');
    stage.innerHTML = '';
    toggleInventory(false);

    if (previewing) {
      var done = onPreviewExit;
      previewing = false;
      onPreviewExit = null;
      if (done) done();
      return;
    }

    /* Leaving forgets where you were, so the next visit starts over. */
    try { sessionStorage.removeItem(STORAGE_KEY); } catch (err) { /* private mode */ }

    if (location.hash === '#labyrinth') {
      history.replaceState(null, '', location.pathname + location.search);
    }
  }

  /* ----------------------------------------------------------------- input */

  function bindGestures() {
    var startX = 0;
    var startY = 0;
    var tracking = false;
    var swiped = false;

    stage.addEventListener('pointerdown', function (e) {
      tracking = true;
      swiped = false;
      startX = e.clientX;
      startY = e.clientY;
    });

    stage.addEventListener('pointerup', function (e) {
      if (!tracking) return;
      tracking = false;

      var dx = e.clientX - startX;
      var dy = e.clientY - startY;

      if (Math.abs(dx) < SWIPE_THRESHOLD && Math.abs(dy) < SWIPE_THRESHOLD) return;
      swiped = true;

      /* Dragging the page up pulls in whatever sits below it, the same way every
         other endless-scroll app works. Same for the other three. */
      if (Math.abs(dy) >= Math.abs(dx)) {
        move(dy < 0 ? 'down' : 'up');
      } else {
        move(dx < 0 ? 'right' : 'left');
      }
    });

    stage.addEventListener('pointercancel', function () { tracking = false; });

    /* a swipe that started on the link shouldn't open the link */
    stage.addEventListener('click', function (e) {
      if (swiped) {
        e.preventDefault();
        swiped = false;
        return;
      }
      var arrow = e.target.closest('.lab-arrow');
      if (arrow) move(arrow.dataset.dir);
    });
  }

  function bindKeys() {
    document.addEventListener('keydown', function (e) {
      if (!active) return;

      if (e.key === 'Escape') {
        toggleInventory(false);
        return;
      }
      var dir = { ArrowUp: 'up', ArrowDown: 'down', ArrowLeft: 'left', ArrowRight: 'right' }[e.key];
      if (!dir) return;

      e.preventDefault();
      move(dir);
    });
  }

  /* ------------------------------------------------------------------ setup */

  function init() {
    root = document.getElementById('labyrinth');
    if (!root) return;

    /* The editor hosts the overlay too, for its test button, and has no toggle. */
    var toggle = document.getElementById('labyrinth-toggle');

    index = indexMaze(loadMaze());

    root.innerHTML =
      '<div class="lab-stage" id="lab-stage"></div>' +
      '<div class="lab-veil" id="lab-veil"></div>' +
      '<button class="lab-pack" id="lab-pack" aria-expanded="false" aria-label="backpack">🎒</button>' +
      '<div class="lab-inventory" id="lab-inventory" hidden></div>';

    stage = root.querySelector('#lab-stage');
    veil = root.querySelector('#lab-veil');
    pack = root.querySelector('#lab-pack');
    inventory = root.querySelector('#lab-inventory');

    buildInventory();
    bindGestures();
    bindKeys();

    if (toggle) {
      /* Going in from the front door always starts at the beginning. Only a
         reload from inside (the #labyrinth case below) picks up where you were. */
      toggle.addEventListener('click', function () { enterLabyrinth(null); });
    }

    pack.addEventListener('click', function () { toggleInventory(); });

    /* the browser's back button should still work — being lost is the joke, being
       trapped isn't */
    window.addEventListener('hashchange', function () {
      if (active && location.hash !== '#labyrinth') exitLabyrinth();
    });

    inventory.addEventListener('click', function (e) {
      var slot = e.target.closest('.lab-slot');
      if (slot) useItem(Number(slot.dataset.item));
    });

    if (location.hash === '#labyrinth') {
      var saved = null;
      try { saved = sessionStorage.getItem(STORAGE_KEY); } catch (err) { /* private mode */ }
      enterLabyrinth(saved);
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

  /* used by _tools/labyrinth-editor.html and _tools/maze-check.js */
  var api = {
    indexMaze: indexMaze,
    reachableFrom: reachableFrom,
    encodeMaze: encodeMaze,
    decodeMaze: decodeMaze,
    loadMaze: loadMaze,
    preview: preview,
    isTunnel: isTunnel,
    tunnelRoute: tunnelRoute,
    pickExit: pickExit,
    DIRS: DIRS,
    DIR_NAMES: DIR_NAMES,
    OPPOSITE: OPPOSITE,
    EFFECTS: EFFECTS,
    TUNNEL_DEFAULTS: TUNNEL_DEFAULTS,
    TUNNEL_HOPS: TUNNEL_HOPS
  };
  if (typeof window !== 'undefined') window.Labyrinth = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})();
